[[signature]]
name = "ASLR Inspection"
alert = "Single"
action = "Kill"
whitelist = ["systemd", "sudo", "ps", ]

[signature.data]
type = "FileAccess"
content = ["/proc/sys/kernel/randomize_va_space"]

[[signature]]
name = "Anti debugging - tracing"
alert = "Single"
action = "Block"
whitelist = ["strace", ]
threat_level = 2

[signature.data]
type = "Syscall"
content = "ptrace"
